apiVersion: v1
kind: Service
metadata:
  name: fakegateway
  labels:
    app: fakegateway
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: fakegateway
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fakegateway-v1
  labels:
    app: fakegateway
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fakegateway
      version: v1
  template:
    metadata:
      labels:
        app: fakegateway
        version: v1
    spec:
      containers:
      - name: fakegateway
        image: dockerniko/fakegateway
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080